CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

This PR fixes a bug where there `BaseUrl` is not set in some code paths when `GetRequestMessageFromRequestInformation` is called.
The PR targets #4 so that the fix may be released together.

Fixes a bug where baseUrl is not set in some scenarios

---

CHANGELOG.md
src/Extensions/HttpRequestMessageExtensions.cs
src/HttpClientRequestAdapter.cs
src/KiotaClientFactory.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
src/Middleware/ChaosHandler.cs
src/Middleware/RetryHandler.cs

This is part of https://github.com/microsoft/kiota-abstractions-dotnet/issues/12
Depends on https://github.com/microsoft/kiota-abstractions-dotnet/pull/14
Changes include: -
- use tryAdd from abstractions
- undo use of deconstructors
- use cast instances of HttpStatusCode and HttpMethod.Patch
- undo use of indexers

Changes target runtime to netstandard2.0

---

CHANGELOG.md
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

This PR is part of This PR is part of https://github.com/microsoft/kiota/issues/1858 
Depends on https://github.com/microsoft/kiota-abstractions-dotnet/pull/41
Changes include
- Align `Send*` methods in `IRequestAdapter` to changes in https://github.com/microsoft/kiota-abstractions-dotnet/pull/41

Changes the responseHandler to be a requestOption

---

src/HttpClientRequestAdapter.cs

Closes https://github.com/microsoft/kiota-http-dotnet/issues/55
Makes the private method name clearer.

Rename ThrowFailedResponse method

---

CHANGELOG.md
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

This PR creates a new release of the library after https://github.com/microsoft/kiota-http-dotnet/pull/61
As the Headers property type has now been updated, the library may throw an error as it currently expects the Headers type to be a dictionary if the older version of Abstractions is used.
This ensures that a version is available with the explicit contraint.

multi-value headers support release

---

.azure-pipelines/ci-build.yml
.github/workflows/build-and_test.yml
CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Extensions/HttpRequestMessageExtensionsTests.cs
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Microsoft.Kiota.Http.HttpClientLibrary.Tests.csproj
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Middleware/ChaosHandlerTests.cs
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Middleware/RedirectHandlerTests.cs
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Middleware/RetryHandlerTests.cs
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Mocks/MockCompressedContent.cs
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
src/Properties/AssemblyInfo.cs

This PR creates a release candidate release for the library
Changes include -
- Ensure the nuget push task uses version greater than 5.2.0 to ensure debug symbols are pushed
- Include readme in nuget package in accordance with https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/
- Adds `net462` target to the test project so that project is tested against NetFramework as well.
- Fixes potential NullReference exceptions discovered as `HttpResponseMessage.Content` can be null in versions of dotnet lower than .NET 5

Release candidate 1

---

.github/workflows/sonarcloud.yml
CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

This PR aligns the HttpClientRequestAdapter with other languages to use the BaseUrl from the RequestAdapter as the baseUrl for making requests.
Reference
- https://github.com/microsoft/kiota-http-go/blob/6ec82d769c78e2a87d3bfa8a87c2cbcbecd5326a/nethttp_request_adapter.go#L206
- https://github.com/microsoft/kiota-java/blob/20a42d0a968ba7460c8cf42f261a4c9da5934d45/components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java#L745

Aligns the BaseUrl for making requests

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Microsoft.Kiota.Http.HttpClientLibrary.Tests.csproj
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1670 and https://github.com/microsoft/kiota-serialization-json-dotnet/issues/69
Conflicting libraries for users on .NET 6 run into issues when forced to use the v7 of the library.
Depends on https://github.com/microsoft/kiota-abstractions-dotnet/pull/73
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1670

Use sliding version for System.Diagnostics.DiagnosticSource and System.Text.Json

---

CHANGELOG.md
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Fixes [Blazor WASM client unable to send web requests through HttpClient BaseAddress microsoft/kiota-http-dotnet#109](https://github.com/microsoft/kiota-http-dotnet/issues/109)
This change allows clients to propagate the BaseUrl through the RequestAdapter's supplied HttpClient instead of needing to set that property explicitly.

Default RequestAdapter BaseUrl to client BaseAddress

---

src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

related https://github.com/microsoft/kiota/issues/2757

- adds missing package icon

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Closes #110 to allow passing of `HttpCompletionOption.ResponseHeadersRead` to HttpClient for Stream responses
Closes #111 by fixing null reference exception observed when the UriTemplate is not set/null

Fixes null reference when template is null

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Ensure the set baseUrl does not end with `\` to avoid incorrect url building.
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1993#issuecomment-1612497330

Trim base url end

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2000
Ensures that streams passed to the `parseNodeFactory` is usable to avoid serialization failures when we should ideally return null.

Fixes a bug where empty streams would be passed to the serializer

---

.github/workflows/build-and_test.yml
CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Middleware/ParametersNameDecodingHandlerTests.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
src/Middleware/ParametersNameDecodingHandler.cs

Closes https://github.com/microsoft/kiota-http-dotnet/issues/137
Also fixes incorrect parameter passed to `DecodeUriEncodedString` to to allow for per request configuration as opposed to the clalss value `EncodingOptions.ParametersToDecode`

Fixes the paramDecodingHandler to only decode query parameter names

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Middleware/ActivitySourceRegistryTests.cs
src/KiotaClientFactory.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
src/Middleware/ActivitySourceRegistry.cs
src/Middleware/ChaosHandler.cs
src/Middleware/CompressionHandler.cs
src/Middleware/HeadersInspectionHandler.cs
src/Middleware/ParametersNameDecodingHandler.cs
src/Middleware/RedirectHandler.cs
src/Middleware/RetryHandler.cs
src/Middleware/UriReplacementHandler.cs
src/Middleware/UserAgentHandler.cs

Adds registry for activity sources 

---

.azure-pipelines/ci-build.yml
.github/workflows/build-and_test.yml
.github/workflows/sonarcloud.yml
CHANGELOG.md
Kiota.Generated/KiotaGenerated.csproj
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Microsoft.Kiota.Http.HttpClientLibrary.Tests.csproj
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Adds support for net8
Related to https://github.com/microsoft/kiota-serialization-json-dotnet/issues/105

Support for net8

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Extensions/HttpRequestMessageExtensionsTests.cs
src/Extensions/HttpRequestMessageExtensions.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

The `CloneAsync` extension method for `HttpRequestMessage` calls `ReadAsStreamAsync` to get the stream contents of a request when cloning the request which will simply [return the same underlying stream](https://github.com/dotnet/runtime/blob/f38242bd94e4ba67c8b985ffe4d52bd04cc2a36c/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L262) object of the request message. 
This therefore means that disposing or seeking the content of the original object will also affect the content of the cloned object as well.
This PR therefore fixes the implementation to use `CopyToAsync` so that a new copy is created to avoid unintended consequences when working with the clone or the original. Tests have been added to validate this as well.

Fixes a bug with `CloneAsync` extension method.

---

CHANGELOG.md
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Updates target framework to include net6.0 and net8.0
Relates to https://github.com/microsoft/kiota-abstractions-dotnet/issues/196

Add net6.0 and net8.0 as Target Frameworks

---

.azure-pipelines/ci-build.yml

Follow up to https://github.com/microsoft/kiota-http-dotnet/pull/214
Fixes deploy task to use compliant `1ES.PublishNuGet@1` task

Fixes release pipeline

---

CHANGELOG.md
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

The dependencies have been optimised for the newer TFM by leveraging version provided natively by the framework.
Closes #230

#230 Leverage framework to optimise dependencies

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/KiotaClientFactoryTests.cs
src/KiotaClientFactory.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Fixes #237 
Enables `WinHttpHandler` as default final handler to unlock http/2 scenarions in Http/2

Fixes errors in NetFramework for http/2 scenarions

---

CHANGELOG.md
src/Extensions/HttpRequestMessageExtensions.cs
src/HttpClientRequestAdapter.cs
src/Middleware/ChaosHandler.cs
src/Middleware/CompressionHandler.cs
src/Middleware/HeadersInspectionHandler.cs
src/Middleware/RedirectHandler.cs
src/Middleware/RetryHandler.cs
src/Middleware/TelemetryHandler.cs
src/Middleware/UriReplacementHandler.cs

Closes #240 by adding `ConfigureAwait(false)` to all async calls in the `HttpClientLibrary` project. I assume no continuations in this repository need to be marshalled back to the original context.

Add missing ConfigureAwait(false) calls

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/Middleware/UriReplacementHandlerTests.cs
src/KiotaClientFactory.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
src/Middleware/UriReplacementHandler.cs

Closes #242 assuming it's ideal for `UriReplacementHandler` to be useable out of the box the way the rest of the handlers are, with the following changes:
1. `UriReplacementHandler` respects options set in the `HttpRequestMessage` in addition to an option given to it upon construction. A test is also added for this.
2. `UriReplacementHandler<UriReplacementHandlerOption>` is included as a default handler so it doesn't have to be added manually.

UriReplacementHandler improvements

---

.gitignore
CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/KiotaClientFactoryTests.cs
src/KiotaClientFactory.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

Overloads `create()` to allow passing middleware pipeline list.
closes https://github.com/microsoft/kiota-http-dotnet/issues/144

Add KiotaClientFactory `create()` overload

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/KiotaClientFactoryTests.cs
src/KiotaClientFactory.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

`SocketsHttpHandler` has been the default handler of `HttpClientHandler` since .NET 5. This change uses `SocketsHttpHandler` directly from Kiota, without going through `HttpClientHandler`.
This change also enables `EnableMultipleHttp2Connections`, which improves performance when there are over 100 concurrent requests to the same server.
This can be performance tested by starting a HTTP/2 server that holds connections open for some time, and a client which makes over 100 parallel requests. e.g.
server:
```csharp
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.ConfigureKestrel(k =>
k.ConfigureEndpointDefaults(e =>
e.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2));
var app = builder.Build();
app.MapGet("/", () => Task.Delay(100)); …
```

Use SocketsHttpHandler and EnableMultipleHttp2Connections as default handler

---

CHANGELOG.md
src/KiotaClientFactory.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
src/Middleware/Options/UriReplacementHandlerOption.cs

Related to [this discussion](https://github.com/MicrosoftDocs/openapi-docs/pull/89#discussion_r1596686316) where I want to enable everybody to use dependency injection instead of the self implemented HttpClient factory.
I'm not sure if this code would be better, I don't like the dependency it takes on reflection. But it would reduce it to only have one list to keep.
```csharp
public static IList<DelegatingHandler> CreateDefaultHandlers()
{
return GetDefaultHandlerTypes()
.Select(handlerType => (DelegatingHandler)System.Activator.CreateInstance(handlerType))
.ToList();
}
```
Fixed #254

Access to just the types of the handlers

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/KiotaClientFactoryTests.cs
src/KiotaClientFactory.cs

closes https://github.com/microsoft/kiota-http-dotnet/issues/233

Add parameter to factory method for setting handler options

---

CHANGELOG.md
Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
src/HttpClientRequestAdapter.cs
src/Microsoft.Kiota.Http.HttpClientLibrary.csproj

bugfix: version range for abstractions
